/**
 * Najlepszy-Trener
 * API zapisywania i listowania na treningi sportowe
 *
 * OpenAPI spec version: 1.0.0
 * Contact: najlepszyterner@com.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Certificate } from './certificate';
import { Discipline } from './discipline';
import { Location } from './location';
import { Offer } from './offer';
import { Opinion } from './opinion';
import { Photo } from './photo';
import { Place } from './place';
import { Profile } from './profile';
import { Training } from './training';
import { University } from './university';


export interface ProfileOut extends Profile { 
    description?: string;
    rating?: number;
    avatar?: string;
    registerDate?: string;
    trDisc?: Array<Discipline>;
    trCert?: Array<Certificate>;
    trUni?: Array<University>;
    trLoc?: Array<Location>;
    trPl?: Array<Place>;
    trOff?: Array<Offer>;
    trOp?: Array<Opinion>;
    trTr?: Array<Training>;
    trPh?: Array<Photo>;
}
