/**
 * Najlepszy-Trener
 * API zapisywania i listowania na treningi sportowe
 *
 * OpenAPI spec version: 1.0.0
 * Contact: najlepszyterner@com.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Treningdane { 
    id?: number;
    name?: string;
    surname?: string;
    phone?: number;
    email?: string;
    comment?: string;
    deleteToken?: string;
    trainingId?: number;
    updatedAt?: string;
    createdAt?: string;
}
