export * from './adCertificate.service';
import { AdCertificateService } from './adCertificate.service';
export * from './addopinion.service';
import { AddopinionService } from './addopinion.service';
export * from './addpicture.service';
import { AddpictureService } from './addpicture.service';
export * from './addprice.service';
import { AddpriceService } from './addprice.service';
export * from './addprofilepicture.service';
import { AddprofilepictureService } from './addprofilepicture.service';
export * from './addtrainersplace.service';
import { AddtrainersplaceService } from './addtrainersplace.service';
export * from './addtraining.service';
import { AddtrainingService } from './addtraining.service';
export * from './cennik.service';
import { CennikService } from './cennik.service';
export * from './city.service';
import { CityService } from './city.service';
export * from './deleteoldtrinings.service';
import { DeleteoldtriningsService } from './deleteoldtrinings.service';
export * from './dyscypline.service';
import { DyscyplineService } from './dyscypline.service';
export * from './editpassword.service';
import { EditpasswordService } from './editpassword.service';
export * from './editprice.service';
import { EditpriceService } from './editprice.service';
export * from './eduni.service';
import { EduniService } from './eduni.service';
export * from './picture.service';
import { PictureService } from './picture.service';
export * from './profile.service';
import { ProfileService } from './profile.service';
export * from './silownia.service';
import { SilowniaService } from './silownia.service';
export * from './trainer.service';
import { TrainerService } from './trainer.service';
export * from './traineroffer.service';
import { TrainerofferService } from './traineroffer.service';
export * from './trainingrezerwation.service';
import { TrainingrezerwationService } from './trainingrezerwation.service';
export * from './trenerDescription.service';
import { TrenerDescriptionService } from './trenerDescription.service';
export * from './updateemailinfo.service';
import { UpdateemailinfoService } from './updateemailinfo.service';
export const APIS = [AdCertificateService, AddopinionService, AddpictureService, AddpriceService, AddprofilepictureService, AddtrainersplaceService, AddtrainingService, CennikService, CityService, DeleteoldtriningsService, DyscyplineService, EditpasswordService, EditpriceService, EduniService, PictureService, ProfileService, SilowniaService, TrainerService, TrainerofferService, TrainingrezerwationService, TrenerDescriptionService, UpdateemailinfoService];
